import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerContainer: {
    paddingTop: 16,
    paddingHorizontal: 24,
    alignItems: 'flex-end',
  },
  skipButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  skipText: {
    fontSize: 16,
    fontWeight: '600',
  },
  header: {
    paddingTop: 16,
    paddingHorizontal: 24,
    paddingBottom: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 20,
    opacity: 0.5,
    paddingHorizontal: 20,
    lineHeight: 18,
  },
  brandTabsContainer: {
    height: 80,
  },
  brandTabsScroll: {
    paddingHorizontal: 24,
    
  },
  brandTab: {
    paddingHorizontal: 18,
    paddingVertical: 0,
    marginRight: 10,
    borderRadius: 20,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    // bottom:8
  },
  brandTabText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.2,
    includeFontPadding: false,
  },
  searchContainer: {
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    padding: 0,
    marginLeft: 12,
  },
  vehicleGrid: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 140,
  },
  vehicleCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 0,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  vehicleCardSelected: {
    borderWidth: 2.5,
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  vehicleImageContainer: {
    width: '100%',
    height: 130,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F8F9FA',
  },
  vehicleImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F8F9FA',
  },
  selectedBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  vehicleNameContainer: {
    padding: 12,
    paddingTop: 8,
    paddingBottom: 12,
    minHeight: 50,
    justifyContent: 'center',
  },
  vehicleName: {
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 17,
  },
  vehicleNameSelected: {
    fontWeight: '700',
  },
  emptyContainer: {
    padding: 60,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  emptyText: {
    fontSize: 16,
    marginTop: 12,
    opacity: 0.5,
  },
  emptySubText: {
    fontSize: 14,
  },
  addVehicleButton: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 36,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  addVehicleButtonContent: {
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  addVehicleButtonText: {
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  addVehicleButtonDisabled: {
    opacity: 0.5,
  },
  columnWrapper: {
    justifyContent: 'space-between',
  },
  flatListEmpty: {
    flex: 1,
  },
});

