import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from '@/theme/metrics';
import { scaledFontSize } from '@/theme/font';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerContainer: {
    paddingTop: verticalScale(16),
    paddingHorizontal: scale(24),
    alignItems: 'flex-end',
  },
  skipButton: {
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(12),
  },
  skipText: {
    fontSize: scaledFontSize(16),
    fontWeight: '600',
  },
  header: {
    paddingTop: verticalScale(16),
    paddingHorizontal: scale(24),
    paddingBottom: verticalScale(16),
  },
  title: {
    fontSize: scaledFontSize(28),
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: verticalScale(6),
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: scaledFontSize(13),
    textAlign: 'center',
    marginBottom: verticalScale(20),
    opacity: 0.5,
    paddingHorizontal: scale(20),
    lineHeight: scaledFontSize(13) * 1.4,
  },
  brandTabsContainer: {
    height: verticalScale(80),
  },
  brandTabsScroll: {
    paddingHorizontal: scale(24),
    
  },
  brandTab: {
    paddingHorizontal: scale(18),
    paddingVertical: 0,
    marginRight: scale(10),
    borderRadius: moderateScale(20),
    height: verticalScale(40),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    // bottom:8
  },
  brandTabText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.2,
    includeFontPadding: false,
  },
  searchContainer: {
    paddingHorizontal: scale(24),
    marginBottom: verticalScale(20),
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: moderateScale(16),
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(14),
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    fontSize: scaledFontSize(15),
    padding: 0,
    marginLeft: scale(12),
  },
  vehicleGrid: {
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(8),
    paddingBottom: verticalScale(140),
  },
  vehicleCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(18),
    padding: 0,
    marginBottom: verticalScale(16),
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  vehicleCardSelected: {
    borderWidth: 2.5,
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  vehicleImageContainer: {
    width: '100%',
    height: verticalScale(130),
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F8F9FA',
  },
  vehicleImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F8F9FA',
  },
  selectedBadge: {
    position: 'absolute',
    top: verticalScale(10),
    right: scale(10),
    width: moderateScale(32),
    height: verticalScale(32),
    borderRadius: moderateScale(16),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  vehicleNameContainer: {
    padding: scale(12),
    paddingTop: verticalScale(8),
    paddingBottom: verticalScale(12),
    minHeight: verticalScale(50),
    justifyContent: 'center',
  },
  vehicleName: {
    fontSize: scaledFontSize(13),
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: scaledFontSize(13) * 1.3,
  },
  vehicleNameSelected: {
    fontWeight: '700',
  },
  emptyContainer: {
    padding: scale(60),
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  emptyText: {
    fontSize: scaledFontSize(16),
    marginTop: verticalScale(12),
    opacity: 0.5,
  },
  emptySubText: {
    fontSize: scaledFontSize(14),
  },
  addVehicleButton: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: scale(24),
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(36),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  addVehicleButtonContent: {
    borderRadius: moderateScale(16),
    paddingVertical: verticalScale(18),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  addVehicleButtonText: {
    fontSize: scaledFontSize(17),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  addVehicleButtonDisabled: {
    opacity: 0.5,
  },
  columnWrapper: {
    justifyContent: 'space-between',
  },
  flatListEmpty: {
    flex: 1,
  },
});

