import { StyleSheet } from 'react-native';

export const createStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.backgrounds.primary,
    },
    map: {
      flex: 1,
    },
    header: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      paddingTop: 60,
      paddingHorizontal: 16,
      paddingBottom: 16,
      backgroundColor: 'transparent',
      zIndex: 20,
    },
    headerGradient: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '120%',
      zIndex: -1,
    },
    topRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      paddingHorizontal: 16,
    },
    vehicleSelector: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
      marginRight: 12,
    },
    vehicleInfo: {
      flex: 1,
    },
    vehicleName: {
      fontSize: 14,
      fontWeight: '600',
      color: '#FFFFFF',
    },
    vehicleNumber: {
      fontSize: 12,
      color: 'rgba(255, 255, 255, 0.7)',
    },
    milesButton: {
      backgroundColor: '#F59E0B',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      marginRight: 8,
    },
    milesButtonText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#FFFFFF',
    },
    profileButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 4,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 12,
      marginHorizontal: 16,
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.text.primary,
      padding: 0,
    },
    filterIcon: {
      padding: 4,
    },
    filtersContainer: {
      flexDirection: 'row',
      gap: 12,
      marginHorizontal: 16,
    },
    filterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 0,
    },
    filterChipActive: {
      backgroundColor: theme.colors.primary[400],
      borderColor: theme.colors.primary[400],
    },
    filterChipInactive: {
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
    },
    filterChipText: {
      fontSize: 12,
      fontWeight: '500',
      marginLeft: 4,
    },
    filterChipTextActive: {
      color: '#FFFFFF',
    },
    filterChipTextInactive: {
      color: theme.colors.text.primary,
    },
    floatingButtons: {
      position: 'absolute',
      right: 16,
      bottom: 140,
      gap: 12,
      zIndex: 30,
      elevation: 6,
    },
    floatingButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.backgrounds.card,
      alignItems: 'center',
      justifyContent: 'center',
      ...theme.shadows.lg,
    },
    locationButton: {
      position: 'absolute',
      left: 16,
      bottom: 140,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.backgrounds.card,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 30,
      elevation: 6,
      ...theme.shadows.lg,
    },
    stationListContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      paddingVertical: 12,
      // paddingLeft: 16,
      backgroundColor: 'transparent',
      zIndex: 10,
      height: 120,
      // paddingHorizontal: 16,
     
    },
    stationListScroll: {
      paddingHorizontal: 16,
    },
    bottomSheetWrapper: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 50,
      elevation: 50,
      pointerEvents: 'box-none',
    },
  });

