import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from '@/theme/metrics';
import { scaledFontSize } from '@/theme/font';

export const createStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.backgrounds.primary,
    },
    map: {
      flex: 1,
    },
    header: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      paddingTop: verticalScale(60),
      paddingHorizontal: scale(16),
      paddingBottom: verticalScale(16),
      backgroundColor: 'transparent',
      zIndex: 20,
    },
    headerGradient: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '120%',
      zIndex: -1,
    },
    topRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: verticalScale(12),
      paddingHorizontal: scale(16),
    },
    vehicleSelector: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      paddingHorizontal: scale(16),
      paddingVertical: verticalScale(10),
      borderRadius: moderateScale(8),
      marginRight: scale(12),
    },
    vehicleInfo: {
      flex: 1,
    },
    vehicleName: {
      fontSize: scaledFontSize(14),
      fontWeight: '600',
      color: '#FFFFFF',
    },
    vehicleNumber: {
      fontSize: scaledFontSize(12),
      color: 'rgba(255, 255, 255, 0.7)',
    },
    milesButton: {
      backgroundColor: '#F59E0B',
      paddingHorizontal: scale(16),
      paddingVertical: verticalScale(8),
      borderRadius: moderateScale(20),
      marginRight: scale(8),
    },
    milesButtonText: {
      fontSize: scaledFontSize(12),
      fontWeight: '600',
      color: '#FFFFFF',
    },
    profileButton: {
      width: moderateScale(44),
      height: verticalScale(44),
      borderRadius: moderateScale(22),
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: scale(4),
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: moderateScale(8),
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(10),
      marginBottom: verticalScale(12),
      marginHorizontal: scale(16),
    },
    searchIcon: {
      marginRight: scale(8),
    },
    searchInput: {
      flex: 1,
      fontSize: scaledFontSize(14),
      color: theme.colors.text.primary,
      padding: 0,
    },
    filterIcon: {
      padding: scale(4),
    },
    filtersContainer: {
      flexDirection: 'row',
      gap: scale(12),
      marginHorizontal: scale(16),
    },
    filterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: scale(16),
      paddingVertical: verticalScale(8),
      borderRadius: moderateScale(20),
      borderWidth: 0,
    },
    filterChipActive: {
      backgroundColor: theme.colors.primary[400],
      borderColor: theme.colors.primary[400],
    },
    filterChipInactive: {
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
    },
    filterChipText: {
      fontSize: scaledFontSize(12),
      fontWeight: '500',
      marginLeft: scale(4),
    },
    filterChipTextActive: {
      color: '#FFFFFF',
    },
    filterChipTextInactive: {
      color: theme.colors.text.primary,
    },
    floatingButtons: {
      position: 'absolute',
      right: scale(16),
      bottom: verticalScale(140),
      gap: scale(12),
      zIndex: 30,
      elevation: 6,
    },
    floatingButton: {
      width: moderateScale(40),
      height: verticalScale(40),
      borderRadius: moderateScale(20),
      backgroundColor: theme.colors.backgrounds.card,
      alignItems: 'center',
      justifyContent: 'center',
      ...theme.shadows.lg,
    },
    locationButton: {
      position: 'absolute',
      left: scale(16),
      bottom: verticalScale(140),
      width: moderateScale(40),
      height: verticalScale(40),
      borderRadius: moderateScale(20),
      backgroundColor: theme.colors.backgrounds.card,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 30,
      elevation: 6,
      ...theme.shadows.lg,
    },
    stationListContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      paddingVertical: verticalScale(12),
      // paddingLeft: 16,
      backgroundColor: 'transparent',
      zIndex: 10,
      height: verticalScale(120),
      // paddingHorizontal: 16,
     
    },
    stationListScroll: {
      paddingHorizontal: scale(16),
    },
    bottomSheetWrapper: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 50,
      elevation: 50,
      pointerEvents: 'box-none',
    },
  });

